# Generated by Django 4.0.4 on 2022-05-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('level', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('department', models.CharField(choices=[('General', 'General'), ('AI', 'AI'), ('CS', 'CS'), ('IS', 'IS'), ('IT', 'IT'), ('DS', 'DS')], max_length=7)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Email', models.CharField(max_length=20)),
                ('Date_of_birth', models.DateField()),
                ('phoneNumber', models.CharField(max_length=11)),
            ],
        ),
    ]
